# spring configuration
spring:
   application:
      name: mysite06
   
   devtools:
      restart:
         enabled: true
      livereload:
         enabled: true
   main:
      allow-bean-definition-overriding: true
   # aop
   aop:
      auto: true
      proxy-target-class: true #aop proxy 적용방식
# server configuration
server:
   port: 8080
   servlet:
      context-path: /mysite06	 